### ISSUE TITLE
Would you consider supporting the YOLOv8-p2 model？

### ISSUE THREAD

**Issue by Fiorentinar** [siyuanliii/masa#14]
Thanks for your excellent work！

I noticed that the MASA config does not include the latest YOLO networks (YOLOv8-v10).

May I ask if you are considering supporting the YOLOv8-p2 model?  Or can you support the standard YOLOv8 model?

**Comment by siyuanliii** [comment]
Thanks a lot for your interest! MASA can directly support all detectors in mmdetection. It seems YOLOv8-p2 is not included in mmdetection yet.  However, it should be simple to add it in the demo file by yourself. You just need to replace the bounding boxes input to the output of YOLOv8 detector.  I will also try to include it in the next phase update.

**Comment by Fiorentinar** [comment]
Thank you for your response. My understanding of the mmdetection framework is not deep enough, but I will try to write the config for it. Thank you for your help.

**Comment by gurkirt** [comment]
@siyuanliii @Fiorentinar, I am able to run [yolov10](https://github.com/THU-MIG/yolov10) which is based on yolov8. If you want I can do a PR?

**Comment by Fiorentinar** [comment]
@gurkirt Thank you very much for your contribution, but this requires the author's consent @siyuanliii.

**Comment by siyuanliii** [comment]
Thank you very much! Please feel free to add PRs. I will review all PRs later and merge them.

**Comment by lonnylundsten** [comment]
> @siyuanliii @Fiorentinar, I am able to run [yolov10](https://github.com/THU-MIG/yolov10) which is based on yolov8. If you want I can do a PR?

Is the yolov10 integration available somewhere?
