### ISSUE TITLE
lost tracking if an object out of screen and back later

### ISSUE THREAD

**Issue by s1n1o1w** [siyuanliii/masa#28]
Hello, first of all, thank you for your nice work.But I found that if an object get out and back later, the MASA will lost tracking of the object.Is this problem happen when you are testing?

**Comment by s1n1o1w** [comment]
today I try to print some information, and I found that before the object get out of screen, it has a instance_id as 0，but when it get out and back later,  its instance_id  has been set as 103, totally different from the beginning

**Comment by siyuanliii** [comment]
Hi! Thanks for your question! There is a hyperparameter in the tracker configure file called [`memo_tracklet_frames`](https://github.com/siyuanliii/masa/blob/1d5d42cdd75276c9a8e918639907916f75a761da/configs/masa-gdino/masa_gdino_swinb_inference.py#L182C9-L182C29). The default setting is 10, which means we only store 10 frames in the memory. You can increase it depending on your framerate and your occlusion time, for instance, for a 30 FPS video, memo_tracklet_frames=300, means you have 10s memory. If the objects disappear within 10s and come back, you can still track them.

**Comment by s1n1o1w** [comment]
That is grate!! Thank you for your reply, and your nice work again
