### ISSUE TITLE
About YOLOX weight

### ISSUE THREAD

**Issue by docShen** [siyuanliii/masa#30]
Thank you for your outstanding work. May I ask, it seems that the YOLOX-x model mentioned here was not obtained from the YOLOX official website GitHub (because the YOLOX-x weights provided in this project are different from the size of the YOLOX-x model on the YOLOX official website), but I need to retrain this model. How can I retrain YOLOX-x.  
Thank you！

**Comment by rolson24** [comment]
For the YOLOX detector, I’m pretty sure MASA does not use the detector as a
feature backbone, the plug and play masa adapter has its own RCNN backbone
to get the features directly from the image. So you can use any old
detector and just pass the detections and the image into the MASA adapter.
