### ISSUE TITLE
TrackDataPreprocessor can not find definition

### ISSUE THREAD

**Issue by jamefrank** [siyuanliii/masa#36]
![image](https://github.com/user-attachments/assets/9b3ad213-9af0-4e4c-8459-27df0adc83af)
where is definition of TrackDataPreprocessor ?

**Comment by siyuanliii** [comment]
Thanks for the question! It is in the mmdetection library

**Comment by jamefrank** [comment]
> Thanks for the question! It is in the mmdetection library

Amazing quick reply!!!
i have found this 
![image](https://github.com/user-attachments/assets/07802970-f2cf-4137-920f-a18dcc7dfc21)
and i also want to know how can i study mmXX by documents
i found nothing about TrackDataPreprocessor ,can you give me some suggestions

**Comment by siyuanliii** [comment]
Yes, it has poor documentation of mmxx. A good way is to just run the step-by-step debugging to figure it out! :)
