### ISSUE TITLE
question on pipeline for training

### ISSUE THREAD

**Issue by nikky4D** [siyuanliii/masa#4]
In the paper, you utilize MASA with SAM, and detector models like Grounding DINO. I did not understand the inference pipeline with detectors and how to apply it for other domains.

Is the masa module first trained with SAM, then the detector head removed and then masa is utilized with Grounding DINO as a feature extractor? If masa is to be applied for other domains without exhaustive SAM segmentations, can masa be used with other segmentation modules? how much data does masa require to develop good features?

**Comment by siyuanliii** [comment]
Thanks for the question! Yes, the detector head can be removed after training. For masa with SAM, the detection branch may be useful as a fast everything bbox prompt provider. For masa-grounding-dino, yes, we reuse the grounding dino's backbone features. When applying masa to other domains, you can always call SAM to group those raw pixels into exhaustive segments.  In our paper, we use 500K images.

**Comment by nikky4D** [comment]
Thanks for the info.
